import { precacheAndRoute } from 'workbox-precaching';
import { get } from 'idb-keyval';

declare const self: any;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen for PWA Web Push events from the server (works when app is closed / phone is locked)
self.addEventListener('push', (event: any) => {
  let title = 'Giờ Kinh Nguyện';
  let body = 'Hãy mở Sách Kinh của bạn để dâng lời nguyện cầu hằng ngày.';
  let icon = '/icon.png';
  let period = ''; // 'morning' or 'evening'

  if (event.data) {
    try {
      const data = event.data.json();
      const payloadNotification = data.notification || {};
      const payloadData = data.data || {};

      title = payloadNotification.title || payloadData.title || data.title || title;
      body = payloadNotification.body || payloadData.body || data.body || body;
      icon = payloadNotification.icon || payloadData.icon || data.icon || icon;
      period = payloadData.period || data.period || '';
    } catch {
      body = event.data.text() || body;
    }
  }

  const options: any = {
    body,
    icon,
    badge: '/icon.png',
    vibrate: [200, 100, 200],
    data: {
      url: '/'
    }
  };

  event.waitUntil(
    (async () => {
      try {
        if (period === 'morning' || period === 'evening') {
          // 1. Check if the user has pinned a custom prayer for this period
          const dbKey = period === 'morning' ? 'fixed_morning_prayer' : 'fixed_evening_prayer';
          const fixedUid = await get(dbKey);

          if (fixedUid) {
            // 2. Load cached prayers and custom user prayers from IndexedDB
            const cachedPrayers = await get('prismic_prayers_cache');
            const customPrayers = await get('custom_prayers_db');

            const allPrayers = [
              ...(Array.isArray(cachedPrayers) ? cachedPrayers : []),
              ...(Array.isArray(customPrayers) ? customPrayers : [])
            ];

            // 3. Find the prayer matching the pinned UID
            const matched = allPrayers.find((p: any) => p.uid === fixedUid);
            if (matched) {
              title = matched.title;
              // Strip HTML tags for safe notification body presentation
              const cleanContent = (matched.content || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
              options.body = cleanContent.substring(0, 120) + (cleanContent.length > 120 ? '...' : '');
              console.log(`SW: Pinned prayer matched! Pushing custom notification: "${title}"`);
            }
          }
        }
      } catch (err) {
        console.error('Error fetching pinned prayer in Service Worker:', err);
      }

      return self.registration.showNotification(title, options);
    })()
  );
});

// Open the app when the user clicks on the push notification
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any[]) => {
      // Focus on open window if it exists
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      // Or open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});

// Skip waiting and activate immediately when update is requested
self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
