import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Skip waiting and activate immediately when update is requested
self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
