import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen for PWA Web Push events from the server (works when app is closed / phone is locked)
self.addEventListener('push', (event: any) => {
  let title = 'Giờ Kinh Nguyện';
  let body = 'Hãy mở Sách Kinh của bạn để dâng lời nguyện cầu hằng ngày.';
  let icon = '/favicon.svg';

  if (event.data) {
    try {
      const data = event.data.json();
      title = data.title || title;
      body = data.body || body;
      icon = data.icon || icon;
    } catch {
      body = event.data.text() || body;
    }
  }

  const options = {
    body,
    icon,
    badge: '/favicon.svg',
    vibrate: [200, 100, 200],
    data: {
      url: '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Open the app when the user clicks on the push notification
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any[]) => {
      // Focus on open window if it exists
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      // Or open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});
